
import { Language, Level } from './types';

export const PRONUNCIATION_DATA = {
    [Language.ENGLISH]: {
        [Level.BEGINNER]: [
            { id: 'en-beg-1', text: "Hello, how are you today?", translation: "Olá, como você está hoje?" },
            { id: 'en-beg-2', text: "My name is John.", translation: "Meu nome é John." },
            { id: 'en-beg-3', text: "I like to eat pizza.", translation: "Eu gosto de comer pizza." },
            { id: 'en-beg-4', text: "Where is the bathroom?", translation: "Onde fica o banheiro?" },
            { id: 'en-beg-5', text: "Good morning to you.", translation: "Bom dia para você." },
            { id: 'en-beg-6', text: "This is my friend.", translation: "Este é meu amigo." },
            { id: 'en-beg-7', text: "I have a big dog.", translation: "Eu tenho um cachorro grande." },
            { id: 'en-beg-8', text: "She is very happy.", translation: "Ela está muito feliz." },
            { id: 'en-beg-9', text: "Can you help me?", translation: "Você pode me ajudar?" },
            { id: 'en-beg-10', text: "The sky is blue.", translation: "O céu é azul." },
            { id: 'en-beg-11', text: "I want some water.", translation: "Eu quero um pouco de água." },
            { id: 'en-beg-12', text: "It is sunny outside.", translation: "Está ensolarado lá fora." },
            { id: 'en-beg-13', text: "Thank you very much.", translation: "Muito obrigado." },
            { id: 'en-beg-14', text: "See you later.", translation: "Vejo você mais tarde." },
            { id: 'en-beg-15', text: "I love my family.", translation: "Eu amo minha família." },
            { id: 'en-beg-16', text: "What time is it?", translation: "Que horas são?" },
            { id: 'en-beg-17', text: "The cat is sleeping.", translation: "O gato está dormindo." },
            { id: 'en-beg-18', text: "Do you speak English?", translation: "Você fala inglês?" },
            { id: 'en-beg-19', text: "I am learning fast.", translation: "Eu estou aprendendo rápido." },
            { id: 'en-beg-20', text: "This book is good.", translation: "Este livro é bom." },
            { id: 'en-beg-21', text: "Please open the door.", translation: "Por favor, abra a porta." },
            { id: 'en-beg-22', text: "I have a red car.", translation: "Eu tenho um carro vermelho." },
            { id: 'en-beg-23', text: "Let's go to the park.", translation: "Vamos ao parque." },
            { id: 'en-beg-24', text: "The apple is sweet.", translation: "A maçã é doce." },
            { id: 'en-beg-25', text: "He is my brother.", translation: "Ele é meu irmão." },
            { id: 'en-beg-26', text: "No problem at all.", translation: "Sem problema nenhum." },
            { id: 'en-beg-27', text: "I need a doctor.", translation: "Eu preciso de um médico." },
            { id: 'en-beg-28', text: "Have a nice day.", translation: "Tenha um bom dia." },
            { id: 'en-beg-29', text: "Where are you from?", translation: "De onde você é?" },
            { id: 'en-beg-30', text: "I live in Brazil.", translation: "Eu moro no Brasil." },
            { id: 'en-beg-31', text: "The food is hot.", translation: "A comida está quente." },
            { id: 'en-beg-32', text: "I am feeling tired.", translation: "Estou me sentindo cansado." },
            { id: 'en-beg-33', text: "Nice to meet you.", translation: "Prazer em conhecer você." },
            { id: 'en-beg-34', text: "Can I come in?", translation: "Posso entrar?" },
            { id: 'en-beg-35', text: "The store is open.", translation: "A loja está aberta." },
            { id: 'en-beg-36', text: "I play soccer well.", translation: "Eu jogo futebol bem." },
            { id: 'en-beg-37', text: "She runs very fast.", translation: "Ela corre muito rápido." },
            { id: 'en-beg-38', text: "We are friends now.", translation: "Nós somos amigos agora." },
            { id: 'en-beg-39', text: "Look at the stars.", translation: "Olhe para as estrelas." },
            { id: 'en-beg-40', text: "Today is Monday.", translation: "Hoje é segunda-feira." }
        ],
        [Level.INTERMEDIATE]: [
            { id: 'en-int-1', text: "I have been working here for five years.", translation: "Eu trabalho aqui há cinco anos." },
            { id: 'en-int-2', text: "Could you please repeat what you just said?", translation: "Você poderia repetir o que acabou de dizer?" },
            { id: 'en-int-3', text: "It looks like it’s going to rain later.", translation: "Parece que vai chover mais tarde." },
            { id: 'en-int-4', text: "She decided to study abroad next semester.", translation: "Ela decidiu estudar fora no próximo semestre." },
            { id: 'en-int-5', text: "I usually drink coffee before starting work.", translation: "Eu geralmente bebo café antes de começar a trabalhar." },
            { id: 'en-int-6', text: "The movie was much better than I expected.", translation: "O filme foi muito melhor do que eu esperava." },
            { id: 'en-int-7', text: "If I were you, I would take that offer.", translation: "Se eu fosse você, aceitaria essa oferta." },
            { id: 'en-int-8', text: "Have you ever been to the United States?", translation: "Você já esteve nos Estados Unidos?" },
            { id: 'en-int-9', text: "I need to stop by the grocery store soon.", translation: "Preciso passar no mercado em breve." },
            { id: 'en-int-10', text: "Although he is tired, he keeps working.", translation: "Embora ele esteja cansado, continua trabalhando." },
            { id: 'en-int-11', text: "Can we reschedule our meeting to Friday?", translation: "Podemos remarcar nossa reunião para sexta-feira?" },
            { id: 'en-int-12', text: "This restaurant serves the best pasta in town.", translation: "Este restaurante serve a melhor massa da cidade." },
            { id: 'en-int-13', text: "She sells seashells by the seashore.", translation: "Ela vende conchas na beira do mar." },
            { id: 'en-int-14', text: "I’m looking forward to hearing from you.", translation: "Estou ansioso para ouvir de você." },
            { id: 'en-int-15', text: "He didn't realize how late it was.", translation: "Ele não percebeu quão tarde era." },
            { id: 'en-int-16', text: "Make sure to turn off the lights.", translation: "Certifique-se de apagar as luzes." },
            { id: 'en-int-17', text: "I prefer tea over coffee in the morning.", translation: "Eu prefiro chá a café de manhã." },
            { id: 'en-int-18', text: "The flight was delayed due to bad weather.", translation: "O voo atrasou devido ao mau tempo." },
            { id: 'en-int-19', text: "Do you mind if I sit here with you?", translation: "Você se importa se eu sentar aqui com você?" },
            { id: 'en-int-20', text: "I have to finish this report by tomorrow.", translation: "Tenho que terminar este relatório até amanhã." },
            { id: 'en-int-21', text: "It takes about an hour to get there.", translation: "Leva cerca de uma hora para chegar lá." },
            { id: 'en-int-22', text: "You should wear a coat, it's cold outside.", translation: "Você deveria usar um casaco, está frio lá fora." },
            { id: 'en-int-23', text: "He is saving money to buy a new car.", translation: "Ele está economizando para comprar um carro novo." },
            { id: 'en-int-24', text: "I am not used to waking up this early.", translation: "Não estou acostumado a acordar tão cedo." },
            { id: 'en-int-25', text: "Let me know if you need any help.", translation: "Me avise se precisar de alguma ajuda." },
            { id: 'en-int-26', text: "The internet connection is very slow today.", translation: "A conexão de internet está muito lenta hoje." },
            { id: 'en-int-27', text: "We went hiking in the mountains last weekend.", translation: "Nós fomos fazer trilha nas montanhas fim de semana passado." },
            { id: 'en-int-28', text: "I was wondering if you are free tonight.", translation: "Eu estava pensando se você está livre hoje à noite." },
            { id: 'en-int-29', text: "Reading books helps expand your vocabulary.", translation: "Ler livros ajuda a expandir seu vocabulário." },
            { id: 'en-int-30', text: "Don't forget to lock the door when you leave.", translation: "Não esqueça de trancar a porta quando sair." },
            { id: 'en-int-31', text: "She is fluent in three different languages.", translation: "Ela é fluente em três idiomas diferentes." },
            { id: 'en-int-32', text: "I accidentally dropped my phone on the floor.", translation: "Eu acidentalmente derrubei meu celular no chão." },
            { id: 'en-int-33', text: "What do you do for a living?", translation: "O que você faz da vida?" },
            { id: 'en-int-34', text: "It's important to drink water every day.", translation: "É importante beber água todos os dias." },
            { id: 'en-int-35', text: "I haven't seen you in a long time.", translation: "Não te vejo há muito tempo." },
            { id: 'en-int-36', text: "The traffic was terrible this morning.", translation: "O trânsito estava terrível esta manhã." },
            { id: 'en-int-37', text: "Can you recommend a good place to visit?", translation: "Você pode recomendar um bom lugar para visitar?" },
            { id: 'en-int-38', text: "I promise I will call you later.", translation: "Eu prometo que te ligo mais tarde." },
            { id: 'en-int-39', text: "Let's split the bill evenly.", translation: "Vamos dividir a conta igualmente." },
            { id: 'en-int-40', text: "Learning a new skill takes time and patience.", translation: "Aprender uma nova habilidade leva tempo e paciência." }
        ],
        [Level.ADVANCED]: [
            { id: 'en-adv-1', text: "The intricacies of quantum physics are fascinating.", translation: "As complexidades da física quântica são fascinantes." },
            { id: 'en-adv-2', text: "He was inexplicably drawn to the mysterious artifact.", translation: "Ele foi inexplicavelmente atraído pelo artefato misterioso." },
            { id: 'en-adv-3', text: "Sustainability is crucial for our planet's future.", translation: "Sustentabilidade é crucial para o futuro do nosso planeta." },
            { id: 'en-adv-4', text: "Her rhetorical skills were evident during the intense debate.", translation: "Suas habilidades retóricas ficaram evidentes durante o debate intenso." },
            { id: 'en-adv-5', text: "The juxtaposition of the two colors created a stunning effect.", translation: "A justaposição das duas cores criou um efeito deslumbrante." },
            { id: 'en-adv-6', text: "Technological advancements have revolutionized modern medicine.", translation: "Avanços tecnológicos revolucionaram a medicina moderna." },
            { id: 'en-adv-7', text: "He articulated his thoughts with precision and clarity.", translation: "Ele articulou seus pensamentos com precisão e clareza." },
            { id: 'en-adv-8', text: "The phenomenon of aurora borealis is best seen at high latitudes.", translation: "O fenômeno da aurora boreal é melhor visto em altas latitudes." },
            { id: 'en-adv-9', text: "Her perseverance in the face of adversity was inspiring.", translation: "Sua perseverança diante da adversidade foi inspiradora." },
            { id: 'en-adv-10', text: "A plethora of opportunities awaits those who are prepared.", translation: "Uma infinidade de oportunidades aguarda aqueles que estão preparados." },
            { id: 'en-adv-11', text: "The cognitive dissonance was overwhelming for him.", translation: "A dissonância cognitiva foi avassaladora para ele." },
            { id: 'en-adv-12', text: "Metaphorically speaking, we are all in the same boat.", translation: "Metaforicamente falando, estamos todos no mesmo barco." },
            { id: 'en-adv-13', text: "The architecture of the building reflects the Victorian era.", translation: "A arquitetura do prédio reflete a era vitoriana." },
            { id: 'en-adv-14', text: "Economic fluctuations can significantly impact global markets.", translation: "Flutuações econômicas podem impactar significativamente os mercados globais." },
            { id: 'en-adv-15', text: "Three thick thighs.", translation: "Três coxas grossas (trava-língua)." },
            { id: 'en-adv-16', text: "How much wood would a woodchuck chuck if a woodchuck could chuck wood?", translation: "Trava-língua clássico da marmota." },
            { id: 'en-adv-17', text: "The kaleidoscope of colors mesmerized the audience.", translation: "O caleidoscópio de cores hipnotizou a plateia." },
            { id: 'en-adv-18', text: "Ubiquitous computing is becoming a reality.", translation: "Computação onipresente está se tornando realidade." },
            { id: 'en-adv-19', text: "The exuberant vegetation covered the ancient ruins.", translation: "A vegetação exuberante cobriu as ruínas antigas." },
            { id: 'en-adv-20', text: "His eccentric behavior was often misunderstood by others.", translation: "Seu comportamento excêntrico era frequentemente mal compreendido." },
            { id: 'en-adv-21', text: "The algorithm utilizes a heuristic approach to solve problems.", translation: "O algoritmo utiliza uma abordagem heurística para resolver problemas." },
            { id: 'en-adv-22', text: "Ebullient and charismatic, she lit up the room.", translation: "Ebuliente e carismática, ela iluminou o ambiente." },
            { id: 'en-adv-23', text: "The dichotomy between good and evil is a common theme.", translation: "A dicotomia entre bem e mal é um tema comum." },
            { id: 'en-adv-24', text: "Procrastination is the thief of time.", translation: "A procrastinação é a ladra do tempo." },
            { id: 'en-adv-25', text: "The symphony was a masterpiece of orchestral composition.", translation: "A sinfonia foi uma obra-prima da composição orquestral." },
            { id: 'en-adv-26', text: "Conscientious employees are highly valued in this company.", translation: "Funcionários conscienciosos são muito valorizados nesta empresa." },
            { id: 'en-adv-27', text: "The epidemiological study revealed interesting patterns.", translation: "O estudo epidemiológico revelou padrões interessantes." },
            { id: 'en-adv-28', text: "Existential questions often plaque great philosophers.", translation: "Questões existenciais frequentemente afligem grandes filósofos." },
            { id: 'en-adv-29', text: "The intricate design of the watch was marvelous.", translation: "O design intrincado do relógio era maravilhoso." },
            { id: 'en-adv-30', text: "Simultaneously, the two events occurred on opposite sides.", translation: "Simultaneamente, os dois eventos ocorreram em lados opostos." },
            { id: 'en-adv-31', text: "The bureaucracy involved in the process was tedious.", translation: "A burocracia envolvida no processo foi entediante." },
            { id: 'en-adv-32', text: "Unprecedented times require unprecedented measures.", translation: "Tempos sem precedentes exigem medidas sem precedentes." },
            { id: 'en-adv-33', text: "The philosophical implications of AI are vast.", translation: "As implicações filosóficas da IA são vastas." },
            { id: 'en-adv-34', text: "He displayed an unparalleled dedication to his craft.", translation: "Ele demonstrou uma dedicação sem paralelo ao seu ofício." },
            { id: 'en-adv-35', text: "Surreptitiously, he glanced at the secret documents.", translation: "Sorrateiramente, ele olhou para os documentos secretos." },
            { id: 'en-adv-36', text: "The quintessential gentleman offered his seat.", translation: "O cavalheiro por excelência ofereceu seu assento." },
            { id: 'en-adv-37', text: "Her ephemeral beauty captivated everyone for a moment.", translation: "Sua beleza efêmera cativou a todos por um momento." },
            { id: 'en-adv-38', text: "The catacombs beneath the city are eerie and dark.", translation: "As catacumbas sob a cidade são assustadoras e escuras." },
            { id: 'en-adv-39', text: "It is imperative that we act immediately.", translation: "É imperativo que ajamos imediatamente." },
            { id: 'en-adv-40', text: "His soliloquy in the third act was heartbreaking.", translation: "Seu solilóquio no terceiro ato foi de partir o coração." }
        ]
    },
    ]
  },
[Language.SPANISH]: {
    [Level.BEGINNER]: [
        { id: 'es-beg-1', text: "Hola, ¿cómo estás?", translation: "Olá, como você está?" },
        { id: 'es-beg-2', text: "Me llamo Juan.", translation: "Meu nome é Juan." },
        { id: 'es-beg-3', text: "Buenos días, señor.", translation: "Bom dia, senhor." },
        { id: 'es-beg-4', text: "¿Dónde está el baño?", translation: "Onde fica o banheiro?" },
        { id: 'es-beg-5', text: "Me gusta la música.", translation: "Eu gosto de música." },
        { id: 'es-beg-6', text: "Gracias por todo.", translation: "Obrigado por tudo." },
        { id: 'es-beg-7', text: "Hasta luego, amigos.", translation: "Até logo, amigos." },
        { id: 'es-beg-8', text: "Necesito ayuda, por favor.", translation: "Preciso de ajuda, por favor." },
        { id: 'es-beg-9', text: "El gato es negro.", translation: "O gato é preto." },
        { id: 'es-beg-10', text: "Quiero beber agua.", translation: "Quero beber água." },
        { id: 'es-beg-11', text: "¿Qué hora es?", translation: "Que horas são?" },
        { id: 'es-beg-12', text: "La casa es grande.", translation: "A casa é grande." },
        { id: 'es-beg-13', text: "Soy de Brasil.", translation: "Sou do Brasil." },
        { id: 'es-beg-14', text: "Me gusta comer tacos.", translation: "Gosto de comer tacos." },
        { id: 'es-beg-15', text: "Ella es mi hermana.", translation: "Ela é minha irmã." },
        { id: 'es-beg-16', text: "El libro está en la mesa.", translation: "O livro está na mesa." },
        { id: 'es-beg-17', text: "Hace calor hoy.", translation: "Faz calor hoje." },
        { id: 'es-beg-18', text: "No entiendo bien.", translation: "Não entendo bem." },
        { id: 'es-beg-19', text: "Hablo un poco de español.", translation: "Falo um pouco de espanhol." },
        { id: 'es-beg-20', text: "El cielo es azul.", translation: "O céu é azul." },
        { id: 'es-beg-21', text: "Vamos a la playa.", translation: "Vamos para a praia." },
        { id: 'es-beg-22', text: "¿Cuánto cuesta esto?", translation: "Quanto custa isto?" },
        { id: 'es-beg-23', text: "Estoy muy cansado.", translation: "Estou muito cansado." },
        { id: 'es-beg-24', text: "Feliz cumpleaños.", translation: "Feliz aniversário." },
        { id: 'es-beg-25', text: "La puerta está abierta.", translation: "A porta está aberta." },
        { id: 'es-beg-26', text: "Me gusta tu coche.", translation: "Gosto do seu carro." },
        { id: 'es-beg-27', text: "Quiero ir a casa.", translation: "Quero ir para casa." },
        { id: 'es-beg-28', text: "El café está caliente.", translation: "O café está quente." },
        { id: 'es-beg-29', text: "Ella canta muy bien.", translation: "Ela canta muito bem." },
        { id: 'es-beg-30', text: "Nosotros somos amigos.", translation: "Nós somos amigos." },
        { id: 'es-beg-31', text: "Trabajo en una oficina.", translation: "Trabalho em um escritório." },
        { id: 'es-beg-32', text: "Me gusta leer libros.", translation: "Gosto de ler livros." },
        { id: 'es-beg-33', text: "Ella tiene un perro.", translation: "Ela tem um cachorro." },
        { id: 'es-beg-34', text: "Hoy es viernes.", translation: "Hoje é sexta-feira." },
        { id: 'es-beg-35', text: "La flor es roja.", translation: "A flor é vermelha." },
        { id: 'es-beg-36', text: "Vivo en una ciudad.", translation: "Moro em uma cidade." },
        { id: 'es-beg-37', text: "El sol brilla fuerte.", translation: "O sol brilha forte." },
        { id: 'es-beg-38', text: "Buenas noches a todos.", translation: "Boa noite a todos." },
        { id: 'es-beg-39', text: "Estoy aprendiendo español.", translation: "Estou aprendendo espanhol." },
        { id: 'es-beg-40', text: "Mucho gusto en conocerte.", translation: "Muito prazer em te conhecer." }
    ],
        [Level.INTERMEDIATE]: [
            { id: 'es-int-1', text: "Me gustaría ordenar una paella, por favor.", translation: "Gostaria de pedir uma paella, por favor." },
            { id: 'es-int-2', text: "El perro corre por el parque rápidamente.", translation: "O cachorro corre pelo parque rapidamente." },
            { id: 'es-int-3', text: "No estoy seguro de qué hacer mañana.", translation: "Não tenho certeza do que fazer amanhã." },
            { id: 'es-int-4', text: "Ella siempre llega tarde a las reuniones.", translation: "Ela sempre chega atrasada nas reuniões." },
            { id: 'es-int-5', text: "Si tuviera dinero, viajaría por el mundo.", translation: "Se eu tivesse dinheiro, viajaria pelo mundo." },
            { id: 'es-int-6', text: "¿Podrías ayudarme con esta tarea?", translation: "Poderia me ajudar com esta tarefa?" },
            { id: 'es-int-7', text: "La comida mexicana es muy picante y rica.", translation: "A comida mexicana é muito picante e rica." },
            { id: 'es-int-8', text: "Espero que tengas un excelente fin de semana.", translation: "Espero que você tenha um excelente fim de semana." },
            { id: 'es-int-9', text: "Mañana por la mañana voy a viajar a Madrid.", translation: "Amanhã de manhã vou viajar para Madrid." },
            { id: 'es-int-10', text: "Lo siento, no puedo ir a tu fiesta.", translation: "Sinto muito, não posso ir à sua festa." },
            { id: 'es-int-11', text: "Creo que va a llover esta tarde.", translation: "Acho que vai chover esta tarde." },
            { id: 'es-int-12', text: "Ella estudia medicina en la universidad.", translation: "Ela estuda medicina na universidade." },
            { id: 'es-int-13', text: "Nosotros fuimos al cine ayer por la noche.", translation: "Nós fomos ao cinema ontem à noite." },
            { id: 'es-int-14', text: "Es importante dormir ocho horas al día.", translation: "É importante dormir oito horas por dia." },
            { id: 'es-int-15', text: "Me encanta caminar por la playa al atardecer.", translation: "Adoro caminhar pela praia ao entardecer." },
            { id: 'es-int-16', text: "¿Has visto mis llaves en algún lugar?", translation: "Você viu minhas chaves em algum lugar?" },
            { id: 'es-int-17', text: "El tráfico en la ciudad es terrible hoy.", translation: "O trânsito na cidade está terrível hoje." },
            { id: 'es-int-18', text: "Prefiero el té en lugar del café.", translation: "Prefiro chá em vez de café." },
            { id: 'es-int-19', text: "Cuando era niño, jugaba mucho al fútbol.", translation: "Quando eu era criança, jogava muito futebol." },
            { id: 'es-int-20', text: "La biblioteca es un lugar muy silencioso.", translation: "A biblioteca é um lugar muito silencioso." },
            { id: 'es-int-21', text: "Voy a comprar un regalo para mi madre.", translation: "Vou comprar um presente para minha mãe." },
            { id: 'es-int-22', text: "El avión despega a las ocho en punto.", translation: "O avião decola às oito em ponto." },
            { id: 'es-int-23', text: "No me gusta el invierno porque hace frío.", translation: "Não gosto do inverno porque faz frio." },
            { id: 'es-int-24', text: "Ella cocina mejor que nadie que conozco.", translation: "Ela cozinha melhor que ninguém que eu conheço." },
            { id: 'es-int-25', text: "Estamos planeando nuestras vacaciones de verano.", translation: "Estamos planejando nossas férias de verão." },
            { id: 'es-int-26', text: "Necesito renovar mi pasaporte pronto.", translation: "Preciso renovar meu passaporte em breve." },
            { id: 'es-int-27', text: "El museo de arte moderno es fascinante.", translation: "O museu de arte moderna é fascinante." },
            { id: 'es-int-28', text: "Siempre olvido dónde estacioné mi coche.", translation: "Sempre esqueço onde estacionei meu carro." },
            { id: 'es-int-29', text: "Hacer ejercicio es bueno para la salud.", translation: "Fazer exercício é bom para a saúde." },
            { id: 'es-int-30', text: "Me gustaría reservar una mesa para dos.", translation: "Gostaria de reservar uma mesa para dois." },
            { id: 'es-int-31', text: "El libro que me prestaste es muy interesante.", translation: "O livro que você me emprestou é muito interessante." },
            { id: 'es-int-32', text: "A veces me gusta estar solo y pensar.", translation: "À vezes gosto de ficar sozinho e pensar." },
            { id: 'es-int-33', text: "La tecnología avanza a pasos agigantados.", translation: "A tecnologia avança a passos gigantescos." },
            { id: 'es-int-34', text: "No sé si podré terminar esto a tiempo.", translation: "Não sei se poderei terminar isto a tempo." },
            { id: 'es-int-35', text: "Ella tiene una voz muy dulce y melodiosa.", translation: "Ela tem uma voz muito doce e melodiosa." },
            { id: 'es-int-36', text: "Vamos a celebrar tu éxito esta noche.", translation: "Vamos celebrar seu sucesso esta noite." },
            { id: 'es-int-37', text: "El paisaje desde la montaña es increíble.", translation: "A paisagem da montanha é incrível." },
            { id: 'es-int-38', text: "Tengo que ir al dentista la próxima semana.", translation: "Tenho que ir ao dentista na próxima semana." },
            { id: 'es-int-39', text: "Me alegra mucho verte de nuevo.", translation: "Fico muito feliz em te ver de novo." },
            { id: 'es-int-40', text: "La vida es una aventura maravillosa.", translation: "A vida é uma aventura maravilhosa." }
        ],
            [Level.ADVANCED]: [
                { id: 'es-adv-1', text: "El ingenioso hidalgo Don Quijote de La Mancha.", translation: "O engenhoso fidalgo Dom Quixote de La Mancha." },
                { id: 'es-adv-2', text: "Tres tristes tigres tragaban trigo en un trigal.", translation: "Três tigres tristes comiam trigo num trigal (trava-língua)." },
                { id: 'es-adv-3', text: "La inefabilidad del sentimiento era abrumadora.", translation: "A inefabilidade do sentimento era avassaladora." },
                { id: 'es-adv-4', text: "Pablito clavó un clavito en la calva de un calvito.", translation: "Pablito pregou um preguinho na careca de um carequinha." },
                { id: 'es-adv-5', text: "La sostenibilidad medioambiental es un desafío global.", translation: "A sustentabilidade ambiental é um desafio global." },
                { id: 'es-adv-6', text: "Su retórica elocuente persuadió a la audiencia.", translation: "Sua retórica eloquente persuadiu a audiência." },
                { id: 'es-adv-7', text: "La yuxtaposición de ideas opuestas fue brillante.", translation: "A justaposição de ideias opostas foi brilhante." },
                { id: 'es-adv-8', text: "El desarrollo cognitivo en la infancia es crucial.", translation: "O desenvolvimento cognitivo na infância é crucial." },
                { id: 'es-adv-9', text: "La paradoja de la vida moderna es ineludible.", translation: "A paradoxo da vida moderna é iniludível." },
                { id: 'es-adv-10', text: "Sus acciones fueron motivadas por altruismo puro.", translation: "Suas ações foram motivadas por altruísmo puro." },
                { id: 'es-adv-11', text: "La epistemología estudia la naturaleza del conocimiento.", translation: "A epistemologia estuda a natureza do conhecimento." },
                { id: 'es-adv-12', text: "Es imprescindible tomar medidas drásticas ahora.", translation: "É imprescindível tomar medidas drásticas agora." },
                { id: 'es-adv-13', text: "La idiosincrasia de este pueblo es única.", translation: "A idiossincrasia deste povo é única." },
                { id: 'es-adv-14', text: "El onirismo en su obra literaria es evidente.", translation: "O onirismo em sua obra literária é evidente." },
                { id: 'es-adv-15', text: "Desafortunadamente, la burocracia ralentiza todo.", translation: "Infelizmente, a burocracia desacelera tudo." },
                { id: 'es-adv-16', text: "La concordancia gramatical es fundamental en español.", translation: "A concordância gramatical é fundamental em espanhol." },
                { id: 'es-adv-17', text: "El caleidoscopio de culturas en esta ciudad es vibrante.", translation: "O caleidoscópio de culturas nesta cidade é vibrante." },
                { id: 'es-adv-18', text: "Su comportamiento errático preocupó a sus familiares.", translation: "Seu comportamento errático preocupou seus familiares." },
                { id: 'es-adv-19', text: "La resiliencia humana frente a la adversidad es notable.", translation: "A resiliência humana frente à adversidade é notável." },
                { id: 'es-adv-20', text: "El existencialismo plantea preguntas profundas.", translation: "O existencialismo levanta perguntas profundas." },
                { id: 'es-adv-21', text: "La serendipia jugó un papel importante en su descubrimiento.", translation: "A serendipidade desempenhou um papel importante em sua descoberta." },
                { id: 'es-adv-22', text: "El sistema judicial debe ser imparcial y justo.", translation: "O sistema judicial deve ser imparcial e justo." },
                { id: 'es-adv-23', text: "La obsolescencia programada es un problema consumista.", translation: "A obsolescência programada é um problema consumista." },
                { id: 'es-adv-24', text: "Sus argumentos eran falaces y carecían de lógica.", translation: "Seus argumentos eram falaciosos e careciam de lógica." },
                { id: 'es-adv-25', text: "La metamorfosis de la oruga en mariposa es bella.", translation: "A metamorfose da lagarta em borboleta é bela." },
                { id: 'es-adv-26', text: "El altruismo recíproco es base de la sociedad.", translation: "O altruísmo recíproco é base da sociedade." },
                { id: 'es-adv-27', text: "La hegemonía cultural influye en nuestros valores.", translation: "A hegemonia cultural influencia nossos valores." },
                { id: 'es-adv-28', text: "Es una situación inverosímil pero posible.", translation: "É uma situação inverossímil mas possível." },
                { id: 'es-adv-29', text: "La quintaesencia del arte renacentista.", translation: "A quintessência da arte renascentista." },
                { id: 'es-adv-30', text: "El vocabulario vernáculo varía según la región.", translation: "O vocabulário vernáculo varia segundo a região." },
                { id: 'es-adv-31', text: "La efímera belleza de los cerezos en flor.", translation: "A efêmera beleza das cerejeiras em flor." },
                { id: 'es-adv-32', text: "Su magnanimidad fue recordada por generaciones.", translation: "Sua magnanimidade foi lembrada por gerações." },
                { id: 'es-adv-33', text: "La inestabilidad geopolítica afecta la economía.", translation: "A instabilidade geopolítica afeta a economia." },
                { id: 'es-adv-34', text: "El debate fue acalorado pero sustancial.", translation: "O debate foi acalorado mas substancial." },
                { id: 'es-adv-35', text: "La dicotomía entre teoría y práctica.", translation: "A dicotomia entre teoria e prática." },
                { id: 'es-adv-36', text: "Su perspicacia para los negocios es inigualable.", translation: "Sua perspicácia para os negócios é inigualável." },
                { id: 'es-adv-37', text: "La ambigüedad de sus palabras causó confusión.", translation: "A ambiguidade de suas palavras causou confusão." },
                { id: 'es-adv-38', text: "El eclecticismo en su estilo de decoración.", translation: "O ecletismo em seu estilo de decoração." },
                { id: 'es-adv-39', text: "La xenofobia es un miedo irracional a lo extranjero.", translation: "A xenofobia é um medo irracional ao estrangeiro." },
                { id: 'es-adv-40', text: "La procrastinación nos impide alcanzar metas.", translation: "A procrastinação nos impede de alcançar metas." }
            ]
},
